# Generated by Django 2.1.4 on 2018-12-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foundation_members',
            new_name='Foundation',
        ),
    ]
